name: Grading

on:
  pull_request:
    paths:
      - 'src/**'
    branches: [ "master", "main" ]

  workflow_dispatch:

jobs:
  print_context:
    runs-on: ubuntu-latest
    environment: homeworks 
    steps:
      - name: Some
        env:
          MISTRAL_KEY: ${{ secrets.MISTRAL_KEY }}
        run: |
          echo "MISTRAL_KEY is: $MISTRAL_KEY"
      - name: Print all environment variables
        run: printenv
      - name: Openai
        run: |
          echo "OpenAO: $OPENAI_KEY"
