name: Grading

on:
  pull_request:
    paths:
      - 'src/**'
    branches: [ "master", "main" ]

  workflow_dispatch:

jobs:
  print_context:
    runs-on: ubuntu-latest
    env:
      MISTRAL_KEY: ${{ secrets.MISTRAL_KEY }}
    steps:
      - run: |
          echo $MISTRAL_KEY
      
